interface SendInviteEmailParams {
  to: string;
  name: string;
  resetPasswordLink: string;
}

interface ResendErrorResponse {
  message?: string;
  name?: string;
}

const companyName = 'Genius Advanced / RIGX';

function getEmailFrom(): string {
  return process.env.INVITE_EMAIL_FROM || 'Genius Advanced / RIGX <onboarding@resend.dev>';
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function buildInviteHtml(params: SendInviteEmailParams): string {
  const name = escapeHtml(params.name);
  const resetPasswordLink = escapeHtml(params.resetPasswordLink);

  return `
    <div style="font-family:Arial,sans-serif;line-height:1.6;color:#0f172a;max-width:600px;margin:0 auto;padding:24px;">
      <h1 style="font-size:22px;margin:0 0 16px;">Welcome to ${companyName}</h1>
      <p>Hi ${name},</p>
      <p>Your staff login account for ${companyName} has been created.</p>
      <p style="margin:24px 0;">
        <a href="${resetPasswordLink}" style="display:inline-block;background:#06b6d4;color:#020617;text-decoration:none;font-weight:700;padding:12px 18px;border-radius:6px;">
          Set Your Password
        </a>
      </p>
      <p>If the button does not work, open this link:</p>
      <p style="word-break:break-all;"><a href="${resetPasswordLink}">${resetPasswordLink}</a></p>
      <p style="margin-top:24px;color:#475569;font-size:13px;">This invite was generated by RIGX ERP.</p>
    </div>
  `;
}

function buildInviteText(params: SendInviteEmailParams): string {
  return [
    `Hi ${params.name},`,
    '',
    `Your staff login account for ${companyName} has been created.`,
    '',
    'Set your password using this link:',
    params.resetPasswordLink,
    '',
    'This invite was generated by RIGX ERP.',
  ].join('\n');
}

export async function sendInviteEmail(params: SendInviteEmailParams): Promise<void> {
  const apiKey = process.env.RESEND_API_KEY;

  if (!apiKey) {
    throw new Error('RESEND_API_KEY is not configured');
  }

  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: getEmailFrom(),
      to: [params.to],
      subject: 'Set your RIGX staff password',
      html: buildInviteHtml(params),
      text: buildInviteText(params),
    }),
  });

  if (!response.ok) {
    let errorBody: ResendErrorResponse | null = null;

    try {
      errorBody = (await response.json()) as ResendErrorResponse;
    } catch {
      errorBody = null;
    }

    throw new Error(errorBody?.message || `Invite email failed with status ${response.status}`);
  }
}
