import type { Timestamp } from 'firebase/firestore';

export type AuditEntityType =
  | 'job'
  | 'payroll'
  | 'leave'
  | 'partner_job'
  | 'customer'
  | 'device'
  | 'parts_order'
  | 'payment'
  | 'warranty_claim'
  | 'schedule'
  | 'notice'
  | 'pos'
  | 'device_checklist';
export type AuditAction =
  | 'create'
  | 'update'
  | 'delete'
  | 'customer_deleted'
  | 'customer_restored'
  | 'notice_deleted'
  | 'notice_restored'
  | 'leave_mc_uploaded'
  | 'status_change'
  | 'quotation_updated'
  | 'quotation_sent'
  | 'quotation_approved'
  | 'quotation_rejected'
  | 'quotation_sent_whatsapp'
  | 'quotation_approved_public'
  | 'quotation_rejected_public'
  | 'job_number_generated'
  | 'job_number_corrected'
  | 'public_repair_tracking_viewed'
  | 'job_tracking_code_generated'
  | 'job_public_update_changed'
  | 'job_tracking_message_sent'
  | 'job_ready_for_pickup_whatsapp_sent'
  | 'job_sheet_consent_token_created'
  | 'job_sheet_manual_consent_recorded'
  | 'job_sheet_customer_signed'
  | 'device_checklist_imported_customer'
  | 'device_checklist_imported_device'
  | 'device_checklist_sent_whatsapp'
  | 'device_checklist_customer_signed'
  | 'device_checklist_signature_overridden'
  | 'job_lifecycle_status_changed'
  | 'job_lifecycle_override_used'
  | 'job_cancelled'
  | 'job_delivered'
  | 'warranty_activated'
  | 'warranty_expired'
  | 'payment_created'
  | 'payment_updated'
  | 'payment_deleted'
  | 'warranty_claim_created'
  | 'warranty_claim_inspection_updated'
  | 'warranty_claim_approved'
  | 'warranty_claim_rejected'
  | 'warranty_claim_completed'
  | 'schedule_created'
  | 'schedule_done'
  | 'schedule_cancelled'
  | 'pos_price_item_created'
  | 'pos_price_item_updated'
  | 'pos_quotation_created'
  | 'pos_quotation_sent'
  | 'pos_quotation_approved'
  | 'pos_quotation_rejected'
  | 'pos_quotation_expired'
  | 'pos_quotation_converted_to_invoice'
  | 'pos_invoice_created'
  | 'pos_invoice_voided'
  | 'pos_payment_recorded'
  | 'pos_payment_reversed'
  | 'pos_refund_created'
  | 'pos_warranty_activated_from_invoice'
  | 'pos_warranty_claim_created'
  | 'pos_warranty_claim_status_updated'
  | 'pos_commission_prepared'
  | 'pos_inventory_movement_prepared'
  | 'pos_commission_approved'
  | 'pos_commission_rejected'
  | 'pos_commission_amount_updated'
  | 'pos_inventory_movement_approved'
  | 'pos_inventory_movement_rejected'
  | 'pos_inventory_movement_applied'
  | 'pos_commission_rule_created'
  | 'pos_commission_rule_updated'
  | 'pos_commission_rule_deactivated'
  | 'pos_commission_rule_activated'
  | 'pos_commission_linked_to_payroll'
  | 'pos_commission_marked_paid'
  | 'pos_inventory_stock_ledger_created'
  | 'inventory_manual_adjustment_created'
  | 'inventory_stock_received'
  | 'inventory_correction_created'
  | 'pos_quotation_public_token_created'
  | 'pos_quotation_customer_viewed'
  | 'pos_quotation_customer_approved'
  | 'pos_quotation_customer_rejected'
  | 'pos_invoice_payment_token_created'
  | 'warranty_terms_token_created'
  | 'warranty_terms_sent_whatsapp'
  | 'warranty_terms_signed'
  | 'pos_payment_submission_created'
  | 'pos_payment_submission_approved'
  | 'pos_payment_submission_rejected'
  | 'pos_quotation_public_token_regenerated'
  | 'pos_quotation_public_token_revoked'
  | 'pos_invoice_payment_token_regenerated'
  | 'pos_invoice_payment_token_revoked'
  | 'pos_invoice_payment_page_viewed'
  | 'pos_ai_pricelist_import_created'
  | 'pos_ai_pricelist_import_parsed'
  | 'pos_ai_pricelist_import_failed'
  | 'pos_ai_pricelist_item_approved'
  | 'pos_ai_pricelist_item_updated_existing'
  | 'pos_ai_pricelist_item_rejected'
  | 'pos_whatsapp_message_sent'
  | 'pos_whatsapp_message_failed'
  | 'whatsapp_message_sent'
  | 'whatsapp_message_failed'
  | 'whatsapp_message_retry_sent'
  | 'whatsapp_message_retry_failed'
  | 'whatsapp_inbound_message_received'
  | 'whatsapp_inbound_message_marked_read'
  | 'whatsapp_inbound_message_archived'
  | 'whatsapp_inbox_reply_sent'
  | 'whatsapp_inbox_reply_failed'
  | 'whatsapp_conversation_assigned'
  | 'whatsapp_conversation_unassigned'
  | 'whatsapp_conversation_status_updated'
  | 'whatsapp_conversation_priority_updated'
  | 'whatsapp_conversation_followup_set'
  | 'whatsapp_conversation_note_added'
  | 'whatsapp_conversation_customer_linked'
  | 'whatsapp_conversation_customer_unlinked'
  | 'whatsapp_conversation_customer_created'
  | 'whatsapp_conversation_entity_linked'
  | 'whatsapp_conversation_entity_unlinked';

export interface AuditChange {
  field: string;
  before: unknown;
  after: unknown;
}

export interface AuditLog {
  auditLogId: string;
  entityType: AuditEntityType;
  entityId: string;
  action: AuditAction;
  changedBy: string;
  changedByDisplayName: string;
  changes: AuditChange[];
  note: string;
  createdAt: Timestamp;
}

export interface CreateAuditLogInput {
  entityType: AuditEntityType;
  entityId: string;
  action: AuditAction;
  changedBy: string;
  changedByDisplayName?: string;
  changes: AuditChange[];
  note?: string;
}
